### PR TITLE
Compatability with newer lush version

### LINKED ISSUE #54: Breaking with latest lush.nvim
Hey 👋🏼,

Cheers for an awesome colorscheme! I just now ran an update and `lush.nvim` was updated. Since then `gruvbox.nvim` is broken and erroring with:

```
packer.nvim: Error running config for gruvbox.nvim: [string "..."]:0: Vim(lua):E5108: Error executing lua ...site/pack/packer/start/gru
vbox.nvim/lua/gruvbox/base.lua:2: module 'lush.hsl.convert' not found:
^Ino field package.preload['lush.hsl.convert']
^Ino file './lush/hsl/convert.lua'
^Ino file '/usr/share/luajit-2.0.5/lush/hsl/convert.lua'
^Ino file '/usr/local/share/lua/5.1/lush/hsl/convert.lua'
^Ino file '/usr/local/share/lua/5.1/lush/hsl/convert/init.lua'
^Ino file '/usr/share/lua/5.1/lush/hsl/convert.lua'
^Ino file '/usr/share/lua/5.1/lush/hsl/convert/init.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/lush/hsl/convert.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/lush/hsl/convert/init.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/lush/hsl/convert.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/lush/hsl/convert/init.lua'
^Ino file './lush/hsl/convert.so'
^Ino file '/usr/local/lib/lua/5.1/lush/hsl/convert.so'
^Ino file '/usr/lib/lua/5.1/lush/hsl/convert.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/lush/hsl/convert.so'
^Ino file './lush.so'
^Ino file '/usr/local/lib/lua/5.1/lush.so'
^Ino file '/usr/lib/lua/5.1/lush.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

### PR DESCRIPTION
**Pull request by jared-mackey**
Lush has renamed a package. Seems to work locally, but would welcome additional testing. Thanks! :) 

closes #54

### CODE REVIEW

**Comment by sQVe** [comment]
Should probably have a look at https://github.com/npxbr/gruvbox.nvim/issues/54#issuecomment-869212501

**Comment by rktjmp** [comment]
You should replace the calls to `hsl_to_hex()` with `.hex` or it's liable to break again. AFAICT the colors are "hsl types".

https://github.com/rktjmp/lush.nvim/blob/97ab088a8de601a71b8c89fdda09fa91612b8755/doc/lush.txt#L206
```
.hex, tostring                                      *lush-color-string-coercion*

Finally, HSL colors can be coerced into a hex string, either by concatenation
with another string, passing to a function which will invoke tostring() or
accessing the `.hex` accessor.

Example                                                     *lush-color-example*
>
  local hsl = require('lush').hsl                 -- include the module
  local red = hsl(0, 100, 50)                     -- define a color
  local light_red = red.lighten(20)               -- modify
  local orange = red.hue(20)                      -- set
  local sum_hues = red.h + light_red.h + orange.h -- access
  local chained_compliment = red.ro(180)          -- chain via aliases
                                .da(30)
                                .sa(10)
  print(red)                                      -- as string "#FF0000"
<
```

**Comment by jared-mackey** [comment]
Ok, changed to `.hex` per recommendation.

**Comment by karlprieb** [comment]
@rktjmp can you merge this PR? Is there something that @jared-mackey need to change?
Thanks

**Comment by rktjmp** [comment]
@karlprieb I am not a gruvbox maintainer, was just tagged in other thread, but your wish has been granted! :tada:

**Pull request merged**
